name: Push rapid_table_det_v to pypi

on:
  push:
    tags:
      - rapid_table_det_v*

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Unit testings
        run: |
          pip install -r requirements.txt
          pip install pytest

          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/cls_det.zip
          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/obj_det_quantized.zip
          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/edge_det_quantized.zip
          unzip cls_det.zip
          unzip obj_det_quantized.zip
          unzip edge_det_quantized.zip
          mv *.onnx rapid_table_det/models/

          pytest tests/test_table_det.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run setup.py
        run: |
          pip install -r requirements.txt
          python -m pip install --upgrade pip
          pip install wheel get_pypi_latest_version

          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/cls_det.zip
          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/obj_det_quantized.zip
          wget https://github.com/Joker1212/RapidTableDetection/releases/download/v0.0.0/edge_det_quantized.zip
          unzip cls_det.zip
          unzip obj_det_quantized.zip
          unzip edge_det_quantized.zip
          mv *.onnx rapid_table_det/models/
          python setup_rapid_table_det.py bdist_wheel "${{ github.ref_name }}"

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
